/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.assignment2.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.mydsl.assignment2.Assignment2Package;
import org.xtext.mydsl.assignment2.ExpMultDiv;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exp Mult Div</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpMultDivImpl extends ExpMinusPlusImpl implements ExpMultDiv
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpMultDivImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Assignment2Package.Literals.EXP_MULT_DIV;
  }

} //ExpMultDivImpl
