/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.assignment2.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.mydsl.assignment2.Assignment2Package;
import org.xtext.mydsl.assignment2.ExpOp;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exp Op</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpOpImpl extends MinimalEObjectImpl.Container implements ExpOp
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpOpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Assignment2Package.Literals.EXP_OP;
  }

} //ExpOpImpl
