/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.ide;

import org.xtext.mydsl.ide.AbstractAssignment2IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Assignment2IdeModule extends AbstractAssignment2IdeModule {
}
