/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mydsl.Assignment2RuntimeModule;
import org.xtext.mydsl.Assignment2StandaloneSetup;
import org.xtext.mydsl.ide.Assignment2IdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class Assignment2IdeSetup extends Assignment2StandaloneSetup {
  @Override
  public Injector createInjector() {
    Assignment2RuntimeModule _assignment2RuntimeModule = new Assignment2RuntimeModule();
    Assignment2IdeModule _assignment2IdeModule = new Assignment2IdeModule();
    return Guice.createInjector(Modules2.mixin(_assignment2RuntimeModule, _assignment2IdeModule));
  }
}
