/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAssignment2ScopeProvider extends DelegatingScopeProvider {
}
