/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.assignment2;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.mydsl.assignment2.Assignment2Factory
 * @model kind="package"
 * @generated
 */
public interface Assignment2Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "assignment2";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/mydsl/Assignment2";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "assignment2";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Assignment2Package eINSTANCE = org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.ModelImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Math</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MATH = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.MathExpImpl <em>Math Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.MathExpImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getMathExp()
   * @generated
   */
  int MATH_EXP = 1;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATH_EXP__EXP = 0;

  /**
   * The number of structural features of the '<em>Math Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATH_EXP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.ExpMinusPlusImpl <em>Exp Minus Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.ExpMinusPlusImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getExpMinusPlus()
   * @generated
   */
  int EXP_MINUS_PLUS = 3;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_MINUS_PLUS__LEFT = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_MINUS_PLUS__OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_MINUS_PLUS__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Exp Minus Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_MINUS_PLUS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.ExpMultDivImpl <em>Exp Mult Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.ExpMultDivImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getExpMultDiv()
   * @generated
   */
  int EXP_MULT_DIV = 2;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_MULT_DIV__LEFT = EXP_MINUS_PLUS__LEFT;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_MULT_DIV__OPERATOR = EXP_MINUS_PLUS__OPERATOR;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_MULT_DIV__RIGHT = EXP_MINUS_PLUS__RIGHT;

  /**
   * The number of structural features of the '<em>Exp Mult Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_MULT_DIV_FEATURE_COUNT = EXP_MINUS_PLUS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.ExpPMImpl <em>Exp PM</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.ExpPMImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getExpPM()
   * @generated
   */
  int EXP_PM = 4;

  /**
   * The number of structural features of the '<em>Exp PM</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_PM_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.ExpMDImpl <em>Exp MD</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.ExpMDImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getExpMD()
   * @generated
   */
  int EXP_MD = 5;

  /**
   * The number of structural features of the '<em>Exp MD</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_MD_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.PrimaryImpl <em>Primary</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.PrimaryImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getPrimary()
   * @generated
   */
  int PRIMARY = 6;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY__LEFT = EXP_MULT_DIV__LEFT;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY__OPERATOR = EXP_MULT_DIV__OPERATOR;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY__RIGHT = EXP_MULT_DIV__RIGHT;

  /**
   * The number of structural features of the '<em>Primary</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_FEATURE_COUNT = EXP_MULT_DIV_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.ParenthesisImpl <em>Parenthesis</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.ParenthesisImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getParenthesis()
   * @generated
   */
  int PARENTHESIS = 7;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS__LEFT = PRIMARY__LEFT;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS__OPERATOR = PRIMARY__OPERATOR;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS__RIGHT = PRIMARY__RIGHT;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS__EXP = PRIMARY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parenthesis</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS_FEATURE_COUNT = PRIMARY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.NumberImpl <em>Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.NumberImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getNumber()
   * @generated
   */
  int NUMBER = 8;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__LEFT = PRIMARY__LEFT;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__OPERATOR = PRIMARY__OPERATOR;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__RIGHT = PRIMARY__RIGHT;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__VALUE = PRIMARY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_FEATURE_COUNT = PRIMARY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.ExpImpl <em>Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.ExpImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getExp()
   * @generated
   */
  int EXP = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__LEFT = EXP_MULT_DIV__LEFT;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__OPERATOR = EXP_MULT_DIV__OPERATOR;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP__RIGHT = EXP_MULT_DIV__RIGHT;

  /**
   * The number of structural features of the '<em>Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_FEATURE_COUNT = EXP_MULT_DIV_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.PlusImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getPlus()
   * @generated
   */
  int PLUS = 10;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = EXP_PM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.MinusImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getMinus()
   * @generated
   */
  int MINUS = 11;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = EXP_PM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.MultImpl <em>Mult</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.MultImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getMult()
   * @generated
   */
  int MULT = 12;

  /**
   * The number of structural features of the '<em>Mult</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_FEATURE_COUNT = EXP_MD_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.assignment2.impl.DivImpl <em>Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.assignment2.impl.DivImpl
   * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getDiv()
   * @generated
   */
  int DIV = 13;

  /**
   * The number of structural features of the '<em>Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_FEATURE_COUNT = EXP_MD_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.mydsl.assignment2.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mydsl.assignment2.Model#getMath <em>Math</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Math</em>'.
   * @see org.xtext.mydsl.assignment2.Model#getMath()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Math();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.MathExp <em>Math Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Math Exp</em>'.
   * @see org.xtext.mydsl.assignment2.MathExp
   * @generated
   */
  EClass getMathExp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mydsl.assignment2.MathExp#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see org.xtext.mydsl.assignment2.MathExp#getExp()
   * @see #getMathExp()
   * @generated
   */
  EReference getMathExp_Exp();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.ExpMultDiv <em>Exp Mult Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp Mult Div</em>'.
   * @see org.xtext.mydsl.assignment2.ExpMultDiv
   * @generated
   */
  EClass getExpMultDiv();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.ExpMinusPlus <em>Exp Minus Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp Minus Plus</em>'.
   * @see org.xtext.mydsl.assignment2.ExpMinusPlus
   * @generated
   */
  EClass getExpMinusPlus();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mydsl.assignment2.ExpMinusPlus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.mydsl.assignment2.ExpMinusPlus#getLeft()
   * @see #getExpMinusPlus()
   * @generated
   */
  EReference getExpMinusPlus_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mydsl.assignment2.ExpMinusPlus#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operator</em>'.
   * @see org.xtext.mydsl.assignment2.ExpMinusPlus#getOperator()
   * @see #getExpMinusPlus()
   * @generated
   */
  EReference getExpMinusPlus_Operator();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mydsl.assignment2.ExpMinusPlus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.mydsl.assignment2.ExpMinusPlus#getRight()
   * @see #getExpMinusPlus()
   * @generated
   */
  EReference getExpMinusPlus_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.ExpPM <em>Exp PM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp PM</em>'.
   * @see org.xtext.mydsl.assignment2.ExpPM
   * @generated
   */
  EClass getExpPM();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.ExpMD <em>Exp MD</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp MD</em>'.
   * @see org.xtext.mydsl.assignment2.ExpMD
   * @generated
   */
  EClass getExpMD();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.Primary <em>Primary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primary</em>'.
   * @see org.xtext.mydsl.assignment2.Primary
   * @generated
   */
  EClass getPrimary();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.Parenthesis <em>Parenthesis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parenthesis</em>'.
   * @see org.xtext.mydsl.assignment2.Parenthesis
   * @generated
   */
  EClass getParenthesis();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mydsl.assignment2.Parenthesis#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see org.xtext.mydsl.assignment2.Parenthesis#getExp()
   * @see #getParenthesis()
   * @generated
   */
  EReference getParenthesis_Exp();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.Number <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number</em>'.
   * @see org.xtext.mydsl.assignment2.Number
   * @generated
   */
  EClass getNumber();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.assignment2.Number#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.mydsl.assignment2.Number#getValue()
   * @see #getNumber()
   * @generated
   */
  EAttribute getNumber_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.Exp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp</em>'.
   * @see org.xtext.mydsl.assignment2.Exp
   * @generated
   */
  EClass getExp();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see org.xtext.mydsl.assignment2.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see org.xtext.mydsl.assignment2.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.Mult <em>Mult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mult</em>'.
   * @see org.xtext.mydsl.assignment2.Mult
   * @generated
   */
  EClass getMult();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.assignment2.Div <em>Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Div</em>'.
   * @see org.xtext.mydsl.assignment2.Div
   * @generated
   */
  EClass getDiv();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Assignment2Factory getAssignment2Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.ModelImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Math</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MATH = eINSTANCE.getModel_Math();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.MathExpImpl <em>Math Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.MathExpImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getMathExp()
     * @generated
     */
    EClass MATH_EXP = eINSTANCE.getMathExp();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MATH_EXP__EXP = eINSTANCE.getMathExp_Exp();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.ExpMultDivImpl <em>Exp Mult Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.ExpMultDivImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getExpMultDiv()
     * @generated
     */
    EClass EXP_MULT_DIV = eINSTANCE.getExpMultDiv();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.ExpMinusPlusImpl <em>Exp Minus Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.ExpMinusPlusImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getExpMinusPlus()
     * @generated
     */
    EClass EXP_MINUS_PLUS = eINSTANCE.getExpMinusPlus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP_MINUS_PLUS__LEFT = eINSTANCE.getExpMinusPlus_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP_MINUS_PLUS__OPERATOR = eINSTANCE.getExpMinusPlus_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP_MINUS_PLUS__RIGHT = eINSTANCE.getExpMinusPlus_Right();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.ExpPMImpl <em>Exp PM</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.ExpPMImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getExpPM()
     * @generated
     */
    EClass EXP_PM = eINSTANCE.getExpPM();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.ExpMDImpl <em>Exp MD</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.ExpMDImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getExpMD()
     * @generated
     */
    EClass EXP_MD = eINSTANCE.getExpMD();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.PrimaryImpl <em>Primary</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.PrimaryImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getPrimary()
     * @generated
     */
    EClass PRIMARY = eINSTANCE.getPrimary();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.ParenthesisImpl <em>Parenthesis</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.ParenthesisImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getParenthesis()
     * @generated
     */
    EClass PARENTHESIS = eINSTANCE.getParenthesis();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARENTHESIS__EXP = eINSTANCE.getParenthesis_Exp();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.NumberImpl <em>Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.NumberImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getNumber()
     * @generated
     */
    EClass NUMBER = eINSTANCE.getNumber();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER__VALUE = eINSTANCE.getNumber_Value();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.ExpImpl <em>Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.ExpImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getExp()
     * @generated
     */
    EClass EXP = eINSTANCE.getExp();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.PlusImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.MinusImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.MultImpl <em>Mult</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.MultImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getMult()
     * @generated
     */
    EClass MULT = eINSTANCE.getMult();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.assignment2.impl.DivImpl <em>Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.assignment2.impl.DivImpl
     * @see org.xtext.mydsl.assignment2.impl.Assignment2PackageImpl#getDiv()
     * @generated
     */
    EClass DIV = eINSTANCE.getDiv();

  }

} //Assignment2Package
