/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.assignment2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp MD</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mydsl.assignment2.Assignment2Package#getExpMD()
 * @model
 * @generated
 */
public interface ExpMD extends EObject
{
} // ExpMD
