/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.assignment2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp Mult Div</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mydsl.assignment2.Assignment2Package#getExpMultDiv()
 * @model
 * @generated
 */
public interface ExpMultDiv extends ExpMinusPlus
{
} // ExpMultDiv
