/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.assignment2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp Minus Plus</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.assignment2.ExpMinusPlus#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.mydsl.assignment2.ExpMinusPlus#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.mydsl.assignment2.ExpMinusPlus#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.assignment2.Assignment2Package#getExpMinusPlus()
 * @model
 * @generated
 */
public interface ExpMinusPlus extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(ExpMinusPlus)
   * @see org.xtext.mydsl.assignment2.Assignment2Package#getExpMinusPlus_Left()
   * @model containment="true"
   * @generated
   */
  ExpMinusPlus getLeft();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.assignment2.ExpMinusPlus#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(ExpMinusPlus value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' containment reference.
   * @see #setOperator(EObject)
   * @see org.xtext.mydsl.assignment2.Assignment2Package#getExpMinusPlus_Operator()
   * @model containment="true"
   * @generated
   */
  EObject getOperator();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.assignment2.ExpMinusPlus#getOperator <em>Operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' containment reference.
   * @see #getOperator()
   * @generated
   */
  void setOperator(EObject value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(ExpMultDiv)
   * @see org.xtext.mydsl.assignment2.Assignment2Package#getExpMinusPlus_Right()
   * @model containment="true"
   * @generated
   */
  ExpMultDiv getRight();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.assignment2.ExpMinusPlus#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(ExpMultDiv value);

} // ExpMinusPlus
