/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.assignment2;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.assignment2.Let#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.mydsl.assignment2.Let#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.assignment2.Assignment2Package#getLet()
 * @model
 * @generated
 */
public interface Let extends Expression
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mydsl.assignment2.Variable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference list.
   * @see org.xtext.mydsl.assignment2.Assignment2Package#getLet_Variable()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getVariable();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Expression)
   * @see org.xtext.mydsl.assignment2.Assignment2Package#getLet_Body()
   * @model containment="true"
   * @generated
   */
  Expression getBody();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.assignment2.Let#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Expression value);

} // Let
