/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.assignment2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Minus</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mydsl.assignment2.Assignment2Package#getMinus()
 * @model
 * @generated
 */
public interface Minus extends ExpOp
{
} // Minus
