/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.assignment2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.assignment2.Model#getMath <em>Math</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.assignment2.Assignment2Package#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Math</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mydsl.assignment2.MathExp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Math</em>' containment reference list.
   * @see org.xtext.mydsl.assignment2.Assignment2Package#getModel_Math()
   * @model containment="true"
   * @generated
   */
  EList<MathExp> getMath();

} // Model
