/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.assignment2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.assignment2.Variable#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.mydsl.assignment2.Variable#getBinding <em>Binding</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.assignment2.Assignment2Package#getVariable()
 * @model
 * @generated
 */
public interface Variable extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.mydsl.assignment2.Assignment2Package#getVariable_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.assignment2.Variable#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Binding</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Binding</em>' containment reference.
   * @see #setBinding(Expression)
   * @see org.xtext.mydsl.assignment2.Assignment2Package#getVariable_Binding()
   * @model containment="true"
   * @generated
   */
  Expression getBinding();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.assignment2.Variable#getBinding <em>Binding</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Binding</em>' containment reference.
   * @see #getBinding()
   * @generated
   */
  void setBinding(Expression value);

} // Variable
