/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.mydsl.assignment2.ui.internal.Assignment2Activator;

public class Assignment2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Assignment2Activator.getInstance().getInjector("org.xtext.mydsl.Assignment2");
	}

}
