/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.mydsl.parser.antlr.internal.InternalAssignment2Parser;
import org.xtext.mydsl.services.Assignment2GrammarAccess;

public class Assignment2Parser extends AbstractAntlrParser {

	@Inject
	private Assignment2GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAssignment2Parser createParser(XtextTokenStream stream) {
		return new InternalAssignment2Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public Assignment2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Assignment2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
