/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Assignment2UiModule extends AbstractAssignment2UiModule {

	public Assignment2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
