/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl;

import org.xtext.mydsl.AbstractAssignment2RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Assignment2RuntimeModule extends AbstractAssignment2RuntimeModule {
}
