/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl;

import org.xtext.mydsl.Assignment2StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Assignment2StandaloneSetup extends Assignment2StandaloneSetupGenerated {
  public static void doSetup() {
    new Assignment2StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
