/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.xtext.mydsl.ui.AbstractAssignment2UiModule;
import org.xtext.mydsl.ui.HoverUI;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Assignment2UiModule extends AbstractAssignment2UiModule {
  public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
    return HoverUI.class;
  }
  
  public Assignment2UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
