/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.ui.contentassist;

import org.xtext.mydsl.ui.contentassist.AbstractAssignment2ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class Assignment2ProposalProvider extends AbstractAssignment2ProposalProvider {
}
