/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mydsl.Assignment2RuntimeModule;
import org.xtext.mydsl.Assignment2StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Assignment2IdeSetup extends Assignment2StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Assignment2RuntimeModule(), new Assignment2IdeModule()));
	}
	
}
