/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.ide;


/**
 * Use this class to register ide components.
 */
public class Assignment2IdeModule extends AbstractAssignment2IdeModule {
}
