/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.validation;

import org.xtext.mydsl.validation.AbstractAssignment2Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class Assignment2Validator extends AbstractAssignment2Validator {
}
