/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Assignment2StandaloneSetup extends Assignment2StandaloneSetupGenerated {

	public static void doSetup() {
		new Assignment2StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
