/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.mydsl.assignment2.ui.internal.Assignment2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Assignment2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Assignment2Activator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Assignment2Activator activator = Assignment2Activator.getInstance();
		return activator != null ? activator.getInjector(Assignment2Activator.ORG_XTEXT_MYDSL_ASSIGNMENT2) : null;
	}

}
